version: '3'

services:
    portfolio:
        image: ghcr.io/remi-espie/remi-espie:latest
        container_name: portfolio
        ports:
            - '8080:80'
# replace files in data folder with your own
#    volumes:
#        - ./data/me.png:/var/www/html/me.png
#        - ./data/CV-REMI_ESPIE.pdf:/var/www/html/CV-REMI_ESPIE.pdf
#        - ./data/CV-REMI_ESPIE-English.pdf:/var/www/html/CV-REMI_ESPIE-English.pdf
